services:
  db:
    image: postgres:15
    container_name: odoo_db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  odoo:
    image: odoo:17.0
    container_name: odoo_container
    ports:
      - "80:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo_web_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    restart: always
volumes:
  odoo_db_data:
  odoo_web_data: